# Generated by Django 4.0.4 on 2022-05-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cousin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('parents', models.CharField(max_length=80)),
                ('birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Family_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Uncle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('birth', models.DateField()),
            ],
        ),
    ]
